#!/usr/bin/env python
# coding: utf-8

ANSI_COLOR_INFO = 'INFO'
ANSI_COLOR_WARN = 'WARN'
ANSI_COLOR_FAIL = 'FAIL'  # short for ERROR
ANSI_COLOR_ERROR = 'ERROR'
ANSI_COLOR_NORMAL = 'NORMAL'
ANSI_COLOR_OK = ' OK '  # short for SUCCESS
ANSI_COLOR_SUCCESS = 'SUCCESS'

ANSI_COLOR_SET = {
    ANSI_COLOR_INFO: '\033[0;36m',
    ANSI_COLOR_WARN: '\033[0;33m',
    ANSI_COLOR_ERROR: '\033[0;31m',
    ANSI_COLOR_NORMAL: '\x1B[0m',
    ANSI_COLOR_SUCCESS: '\x1B[1;36m'}

ANSI_NONE_COLOR_SET = {
    ANSI_COLOR_INFO: '',
    ANSI_COLOR_WARN: '',
    ANSI_COLOR_ERROR: '',
    ANSI_COLOR_NORMAL: '',
    ANSI_COLOR_SUCCESS: ''}

